// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0eVm689uIPFreAEUccsXl4YysiXB-L8o',
    appId: '1:604082756894:web:c254b559d028ae0fe4bd0f',
    messagingSenderId: '604082756894',
    projectId: 'stockscreener-d4e12',
    authDomain: 'stockscreener-d4e12.firebaseapp.com',
    storageBucket: 'stockscreener-d4e12.firebasestorage.app',
    measurementId: 'G-9QBE31PRWT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBECJZt5GmC_oU14eS4P-h7g-TOzPj9Ep0',
    appId: '1:604082756894:android:4a5e4e6175798b9fe4bd0f',
    messagingSenderId: '604082756894',
    projectId: 'stockscreener-d4e12',
    storageBucket: 'stockscreener-d4e12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlCaQV3tgcsLWB8Kvc_vsfediLDUUXfR4',
    appId: '1:604082756894:ios:c43898af3c6c6042e4bd0f',
    messagingSenderId: '604082756894',
    projectId: 'stockscreener-d4e12',
    storageBucket: 'stockscreener-d4e12.firebasestorage.app',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlCaQV3tgcsLWB8Kvc_vsfediLDUUXfR4',
    appId: '1:604082756894:ios:c43898af3c6c6042e4bd0f',
    messagingSenderId: '604082756894',
    projectId: 'stockscreener-d4e12',
    storageBucket: 'stockscreener-d4e12.firebasestorage.app',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0eVm689uIPFreAEUccsXl4YysiXB-L8o',
    appId: '1:604082756894:web:cded100383917350e4bd0f',
    messagingSenderId: '604082756894',
    projectId: 'stockscreener-d4e12',
    authDomain: 'stockscreener-d4e12.firebaseapp.com',
    storageBucket: 'stockscreener-d4e12.firebasestorage.app',
    measurementId: 'G-SM4L6NXC7Z',
  );
}
